import type { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  overwrite: true,
  schema: process.env.GRAPHQL_ENDPOINT || "http://localhost:4000/query",
  generates: {
    "src/graphqlTypes.ts": {
      plugins: [
        "typescript",
        {
          add: {
            content: "// Code generated by graphql-codegen. DO NOT EDIT.\n",
          },
        },
      ],
    },
    "src/": {
      documents: "src/**/!(*.generated).graphql",
      preset: "near-operation-file",
      presetConfig: {
        baseTypesPath: "graphqlTypes.ts",
      },
      plugins: [
        {
          add: {
            content: "// Code generated by graphql-codegen. DO NOT EDIT.\n",
          },
        },
        "typescript-operations",
        "typescript-react-apollo",
      ],
    },
  },
};

export default config;
