// Code generated by graphql-codegen. DO NOT EDIT.

/* eslint-disable @typescript-eslint/naming-convention */
/* eslint-disable todo-comment/ticket-url */
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = {
  [K in keyof T]: T[K];
};
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & {
  [SubKey in K]?: Maybe<T[SubKey]>;
};
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & {
  [SubKey in K]: Maybe<T[SubKey]>;
};
export type MakeEmpty<
  T extends { [key: string]: unknown },
  K extends keyof T,
> = { [_ in K]?: never };
export type Incremental<T> =
  | T
  | {
      [P in keyof T]?: P extends " $fragmentName" | "__typename" ? T[P] : never;
    };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string };
  String: { input: string; output: string };
  Boolean: { input: boolean; output: boolean };
  Int: { input: number; output: number };
  Float: { input: number; output: number };
  DateTime: { input: unknown; output: string };
};

export type CreateTaskInput = {
  description: Scalars["String"]["input"];
  endAt?: InputMaybe<Scalars["DateTime"]["input"]>;
  name: Scalars["String"]["input"];
  startAt?: InputMaybe<Scalars["DateTime"]["input"]>;
};

export type Mutation = {
  createTask?: Maybe<Scalars["ID"]["output"]>;
};

export type MutationCreateTaskArgs = {
  input: CreateTaskInput;
};

export type Query = {
  tasks: TaskCollection;
};

export type Task = {
  description: Scalars["String"]["output"];
  endAt?: Maybe<Scalars["DateTime"]["output"]>;
  id: Scalars["ID"]["output"];
  name: Scalars["String"]["output"];
  startAt?: Maybe<Scalars["DateTime"]["output"]>;
};

export type TaskCollection = {
  collection: Array<Task>;
};
